"use client";
import { useMemo, useState } from "react";
import { Icon } from "./Icons";
import { useStudy } from "./StudyProvider";

export function ResourcesPanel({courseId}:{courseId:string}){
  const {state,addResource,deleteResource}=useStudy();
  const items=useMemo(()=>state.resources.filter((r)=>r.courseId===courseId),[state.resources,courseId]);
  const [show,setShow]=useState(false);const [title,setTitle]=useState("");const [url,setUrl]=useState("");const [type,setType]=useState<"pdf"|"slides"|"link"|"syllabus"|"lab"|"assignment">("link");
  function add(){if(!title.trim()||!url.trim())return;addResource(courseId,{title:title.trim(),url:url.trim(),type});setTitle("");setUrl("");setShow(false)}
  return <div><div className="workspace-toolbar"><div><span className="eyebrow">LIBRARY</span><h3>{items.length} course resources</h3></div><button className="button primary" onClick={()=>setShow(!show)}><Icon name="plus" size={15}/> Add link</button></div>{show&&<div className="inline-form resource-form"><label>Title<input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Week 4 slides"/></label><label>URL<input value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Type<select value={type} onChange={(e)=>setType(e.target.value as typeof type)}><option value="link">Link</option><option value="pdf">PDF</option><option value="slides">Slides</option><option value="syllabus">Syllabus</option><option value="lab">Lab</option><option value="assignment">Assignment</option></select></label><button className="button primary" onClick={add}>Save</button></div>}{items.length?<div className="resource-grid">{items.map((item)=><article key={item.id}><div className="resource-icon"><Icon name={item.type==="link"?"link":"file"}/></div><div><span>{item.type.toUpperCase()}</span><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a><small>{new URL(item.url,"https://local.invalid").hostname.replace("local.invalid","")||item.url}</small></div><button className="icon-button small danger-ghost" onClick={()=>deleteResource(item.id)}><Icon name="trash" size={14}/></button></article>)}</div>:<div className="empty-state"><Icon name="book" size={30}/><h3>Keep every course resource in one place.</h3><p>Add your syllabus, slides, PDFs, lab links and useful references. File storage is wired into the Supabase migration for the backend phase.</p></div>}</div>
}
